---
- name: Copy gnome settings.ini to system.
  copy:
    src: ../files/gnome_settings.ini
    dest: "/home/{{ username }}/.config/gtk-3.0/settings.ini"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664

- name: Enable tap to click.
  command: gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
