---
- name: Add vscodium rpm repo key.
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: Add vscodium rpm repo.
  yum_repository:
    name: vscodium
    description: vscodium rpm repo
    file: external_repos
    baseurl: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/ 
    gpgcheck: yes

- name: Install vscodium.
  dnf:
    name: vscodium
    state: latest

