---
- name: Remove old docker.
  dnf:
    name: ['docker', 'docker-ce', 'docker-compose']
    state: absent

- name: Install dnf config-manager.
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Remove old docker-ce repo file.
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: absent

- name: Move docker-ce custom repo file.
  copy:
    src: ../files/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Install docker-ce.
  dnf:
    name: docker-ce
    state: latest

- name: Install docker-compose.
  dnf:
    name: docker-compose
    state: latest

- name: Add user in group docker.
  user:
    name: "{{ username }}"
    groups: wheel, docker

- include: traefik.yml

